name: Build
on:
  push:
    branches: [master]
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8
          cache: gradle

      - name: Give permissions to Gradle
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build  

  tag:
    name: Create Tag
    runs-on: ubuntu-latest
    
    steps:
      - name: Get current project version
        run: echo "::set-output name=project_version::$(grep '^projectVersion=' gradle.properties | cut -d'=' -f2)"

      - name: Check if tag exists
        id: check_tag
        run: |
          if git rev-parse "refs/tags/steps.check_tag.outputs.project_version >/dev/null 2>&1; then
            echo "::set-output name=tag_exists::true"
          else
            echo "::set-output name=tag_exists::false"
          fi

      - name: Create tag
        if: steps.check_tag.outputs.tag_exists == 'false'
        run: |
          git tag -a steps.check_tag.outputs.project_version -m "Version steps.check_tag.outputs.project_version"
          git push origin steps.check_tag.outputs.project_version