name: Build

on:
  push:
    branches: [master]

permissions:
  contents: write #nessesary for tag creation and release creation

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8
          cache: gradle

      - name: Give permissions to Gradle
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build  

      - name: Get current project version
        run: echo "::set-output name=project_version::$(grep '^projectVersion=' gradle.properties | cut -d'=' -f2)"

      - name: Check if tag exists
        id: check_tag
        run: |
          if git rev-parse "refs/tags/${{ steps.check_tag.outputs.project_version }}" >/dev/null 2>&1; then
            echo "::set-output name=tag_exists::true"
          else
            echo "::set-output name=tag_exists::false"
          fi
          
      - name: Create Release
        if: ${{ format('refs/heads/{0}', github.event.repository.default_branch) == github.ref }} || steps.check_tag.outputs.tag_exists == 'false'
        run: |
          tag=$(git rev-parse --short ${{ github.sha }})
          gh release create "$tag" build/libs/packetlib**.jar \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
              --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}